### ISSUE TITLE
SimpleXMLElement String could not be parsed as XML

### ISSUE THREAD

**Issue by Yippy** [J-Mose/CommandSchedulerBundle#103]
Hi,
I'm having this odd issue where SimpleXMLElement trying to parse a string with Deprecated messages, at the end of the deprecated message the command list xml appears after it.

![error](https://user-images.githubusercontent.com/6518915/38680826-27ce77ce-3e5f-11e8-92f9-86674b67675c.png)

Oddly the list works first time after clearing cache, but second run the Deprecated message brings up this exception.

This is how the list works first time, the design is based on SonataAdmin theme which my project is based on.
![load list](https://user-images.githubusercontent.com/6518915/38680827-27e8e7e4-3e5f-11e8-93e6-66132121acf5.png)

**Comment by Yippy** [comment]
This only happens for development app_dev.php, is the exception meant to appear here?

Accessing via prod app.php is working fine.

**Comment by chrisjohnson00** [comment]
Based on the error message, a deprecated security command is being used: http://api.symfony.com/3.4/Symfony/Bundle/SecurityBundle/Command/InitAclCommand.html
There's a replacement, you may be able to use the new service in place of your current one with little/no changes.  Also, there may be a setting you can change in the debugger/profiler to throw that as a warn rather than an exception... normally I only see notices in the debug bar showing that there are X deprecated methods/classes being used.  A quick search of this project doesn't come up with `initaclcommand` or `security.command.init_acl`, so I'm guessing it's introduced by symfony standard or your project specifically.

**Comment by Yippy** [comment]
Yeah I know I got deprecated API and bundles, just wondering if the SimpleXMLElement meant to parse through a string with those deprecated message to begin with? It loads the command with it in the same string. Hence the exception.. i don't think everyone is expected to have a perfect project just thought I put this down as a issue.

**Comment by Yippy** [comment]
The only way to parse the string correct is to trim everything before '<?xml'

`
    /**
     * Extract an array of available Symfony command from the XML output
     *
     * @param $xml
     * @return array
     */
    private function extractCommandsFromXML($xml)
    {
        $xml = strstr($xml, '<?xml');
        if ($xml == '') {
            return array();
        }
`

While this looks like a fudge it helps removed the deprecated log messages, there should be a better method to check the string is a valid xml format before parsing it through SimpleXMLElement

**Comment by ammont** [comment]
I have the same issue since this class is inside Symfony it's impossible to remove it.

**Comment by Th3BiSh0p** [comment]
Same issue here...

`Warning: SimpleXMLElement::__construct(): Entity: line 2: parser error : Start tag expected, '&lt;' not found`

**Comment by J-Mose** [comment]
see https://github.com/J-Mose/CommandSchedulerBundle/issues/113#issuecomment-438712289
