### ISSUE TITLE
Update to 2.0.1 throws error

### ISSUE THREAD

**Issue by IwfY** [J-Mose/CommandSchedulerBundle#125]
When updating from v2.0.0 to v2.0.1 through composer I get the following error:

```
[WARNING] Some commands could not be registered:                               

In appDevDebugProjectContainer.php line 7291:
                                       
The parameter "s, " must be defined.
```

I'm using it in a Symfony 3.4 application and PHP 7.3.
Maybe it has something to do with parameter escaping ("%%s"). There are a couple of places in the diff:
https://github.com/J-Mose/CommandSchedulerBundle/compare/v2.0.0...v2.0.1

**Comment by BernhardWebstudio** [comment]
The culprit is the config: 
      monitor_mail_subject: cronjob minoring %s, %s
leads symfony to think that the things between the two "%" are a parameter. Just remove one of the %s to get rid of the error if you do not need both placeholders (first placeholder would be replaced by the hostname, second by the date).
Maybe there is a way to escape the %?

**Comment by BernhardWebstudio** [comment]
According to [this answer](https://stackoverflow.com/a/27274304), a double percentage will do. 
The config should therefore look like:

    monitor_mail_subject: cronjob monitoring %%s, %%s

At least this is what fixed it for me. I guess the [documentation](https://github.com/J-Mose/CommandSchedulerBundle/blob/master/Resources/doc/index.md#4---available-configuration) has to be updated?
