### ISSUE TITLE
Allow Symfony 3

### ISSUE THREAD

**Issue by raiviskrumins** [J-Mose/CommandSchedulerBundle#23]
Please make this Bundle available in Symfony 3

**Comment by J-Mose** [comment]
The last release v1.2.0 is now Symfony 3 compatible 
(1.1.x versions still maintain Symfony 2.3 to 2.7)

**Comment by ecoronel1** [comment]
Upgrade composer -> php compatibility

**Comment by J-Mose** [comment]
fixed

**Comment by ecoronel1** [comment]
Can you update composer.json of v1.2.0?... My application is installing this version because in this file "php": ">=5.3.2",

I know that I can set "jmose/command-scheduler-bundle": "1.1.*", but it is better if you set correctly php compatibility in your composer file

**Comment by J-Mose** [comment]
I create a 1.2.1 tag with the new composer.json. (php >= 5.5.9, like symfony)
Do you use "~1.2" in you composer.json ?

I can't delete / recreate an existing tag (this is not a good pratice with packagist and composer cache)

**Comment by ecoronel1** [comment]
I am using symfony 2.8 and  php: 5.4 in my server and set **"php": "5.4.*"** in my composer file to avoid install dependencies that works with another php versions.

When you use (*php composer.phar require jmose/command-scheduler-bundle*) 

Automatically, composer installs (**"jmose/command-scheduler-bundle": "^1.2"**) because v1.2.0 composer's file says that it works with **"php": ">=5.3.2"**. (wrong dependency because it needs php >=5.5)

I am new on this, but that was my problem, I will set **"jmose/command-scheduler-bundle": "1.1.*"** in my composer file to solve it.
