### ISSUE TITLE
Does it work on a windows server ?

### ISSUE THREAD

**Issue by eved42** [J-Mose/CommandSchedulerBundle#48]
I have a project in Symfony3 and it is hosted on a Windows Server.
So, my custom command line should be executed with AT (windows) and not with CRON (unix), right ?

Does this bundle work on a windows server ?
Should I write an AT expression in the Cron expression field ??

Thank you for helping.

**Comment by Glideh** [comment]
It will work only on a real OS... kidding.

I think there is nothing preventing you to use it with Windows Task Scheduler.
You will have to schedule a task in Windows that will run the main `scheduler:execute` command regularly (check the [usage doc section](https://github.com/J-Mose/CommandSchedulerBundle/blob/master/Resources/doc/index.md#usage)).

Concerning the "Cron expression field" you will have to use the standard cron syntax since the bundle seems to rely on a [php implementation](https://github.com/mtdowling/cron-expression)
