### ISSUE TITLE
Lock_timeout is not timeouting commands that run to long

### ISSUE THREAD

**Issue by ghost** [J-Mose/CommandSchedulerBundle#67]
In documentation we have this
```
# This default value disables timeout checking (see monitoring), set to a numeric value (seconds) to enable it
lock_timeout: false
```
If I got it right if change value of lock_timeout I would like CommandChedulerBundle to stop commands that are running at least, given time(in seconds). What is happening? Clearly nothing, I have idea that it is used to email to people when script timeouts, and then someone should manually stop it. I would like also option to automatically stop, because I'm using automatically cron-flow. Thanks

**Comment by chrisjohnson00** [comment]
To ensure this is understood... is this a restatement of what you are looking for?
With a value of `lock_timeout: 3600`, you want the `scheduler:monitor` command to kill the execution of a running command if the run time is >= 3600 seconds?

As you've stated, this value is currently used to alert that a command is running longer than allowed and needs attention.

**Comment by chrisjohnson00** [comment]
not sure this helps you @blastlab-jenkins but you could alter the crontab entry which calls the command scheduler to include using the system timeout program, see https://askubuntu.com/a/102328/355673

**Comment by PianistaMichal** [comment]
It is some kind of workaround I will use for now. But I would like something like config option, just framework-like way, to automatically kill the execution of running command. Something like `timeout_kill: <false/true>` will be nice. For me it could be used by `scheduler:execute` not triggered by `scheduler:monitor` so by given config:
```
lock_timeout: 3600
timeout_kill: true
```
it will automatically kill **each** command after 3600 sec of running. Because the point is to kill command and just kill. It should be `scheduler:execute` responsibility.

**Comment by J-Mose** [comment]
The lock purpose is not to kill the process (even if it would be usefull).

For now, the bundle does not interact with the operating system, none PID are store so it can't kill process or check what is running.

The lock timeout is usefull when a command crash with a fatal error (and then stay locked in scheduler). 

See the lock timeout as way to tell monitoring : After x seconds, the command **probably** crashed and then alert admin.
