### ISSUE TITLE
Parallel execution

### ISSUE THREAD

**Issue by froemken** [J-Mose/CommandSchedulerBundle#70]
Hello,

thank you for this great bundle. It looks pretty good.

I have created multiple tasks. Some tasks needs 2 hours, another one needs 4 hours and all the other tasks are done in less than a minute. I call scheduler:execute each 5 minutes as I have a task (*/5 * * * *) which has to send all mails of a queue.

At 8 o'clock one of my 2 hour task starts. While this execution all my other tasks will start AFTER my 8 o'clock task. So, I can't send mails for a timeframe of 2 hours.

How can I allow parallel execution of my tasks?

Stefan

**Comment by froemken** [comment]
I just see, that you don't call the tasks by exec(), passthrow() or system(). So, my task is still bussy, while executing my long task. Do you think it would be a good idea when I setup 2 or more OS based cronjobs which calls scheduler:execute?

**Comment by chrisjohnson00** [comment]
@froemken - ideally you should invoke the `scheduler:execute` command every minute as this will give you the most "cron-like" experience.  However, you are correct that if 2 tasks execute on the same timer (both start at 5 after), the execution will be serial, unlike a real crontab entry.  So, the bundle uses a priority value (highest value wins).  
I have 2 suggestions for you.

1. Update your `schedule:execute` to run every min.  Update your tasks so that they don't run on the same execution of `scheduler:execute`.  This is a common practice for crontab entries anyway, as to keep resources from being consumed all at once.
2. Update the priority of the tasks.  I would set the long running tasks to be lowest priority, and set the quick running tasks to be higher priority.  This will allow your quick tasks to execute before your long one, if they happen to trigger in the same `scheduler:execute` run.

**Comment by seyfer** [comment]
@froemken, on my opinion, for parallel tasks developer need to use some services like Gearman or RabiitMQ. Cron jobs aren't solving your needs.

**Comment by froemken** [comment]
@seyfer I have created 10 different tasks with J-Moses scheduler. 8 tasks just need up to 10 seconds to execute. The other both tasks can take up to 4 hours. I will never start the same task in parallel. I will start different tasks in parallel.
For now I have created 3 cronjobs which all starts the command of J-Moses scheduler and it works perfectly. If my 4 hours task is running, the mail queue task will run each 5 minutes without waiting until my 4 hour task is finished. IMO that's great. So...yes...my current solution just solves my needs.
